### ISSUE TITLE
Request to make a new release(0.8.2?)

### ISSUE THREAD

**Issue by kenhys** [mattn/growl-for-linux#56]
I want to make growl-for-linux package into Debian GNU/Linux unstable.

Recently, following the typo was fixed, which affects database schema.
https://github.com/mattn/growl-for-linux/pull/54

So I want to make a package which contains above fix.
Please consider to make a new release.

P.S. I'm happy if manually generated tar.gz archive is also available from
https://github.com/mattn/growl-for-linux/releases because auto generated tar.gz by GitHub system lacks configure script in tar.gz archive.

**Comment by mattn** [comment]
okay, will update debian stuff, and do git-tag.

**Comment by kenhys** [comment]
Any progress?

I am working for ITP (Intent to package) and RFS (Request for sponsor).
It is based on 0.8.1 + some patches already sended PR because 0.8.2 is not released yet.
(If 0.8.2 will be released soon or later, I'll update it too.)

ITP: growl-for-linux
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816514

RFS: growl-for-linux/0.8.1-2
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821171

**Comment by mattn** [comment]
tagged 0.8.2

**Comment by mattn** [comment]
Thank for your work. Well, if you work for this, cal I stop working for PPA? I couldn't take enoguh time to release to PPA.

**Comment by kenhys** [comment]
Maybe yes, but it is up to you.
At least, ubuntu syncs package periodically from debian, so new version of growl-for-linux will be also released.
But not for older release which is still supported (15.10 or something). it is meaningful to release on PPA.

**Comment by kenhys** [comment]
Thank you for tagging. I'll update RFS.
