### ISSUE TITLE
License issue about bundled images

### ISSUE THREAD

**Issue by kenhys** [mattn/growl-for-linux#62]
I'm working on debian packaging  and there is a concern about license issue during RFS process.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821171

In short, it seems that proprietary icons should be replaced.
Typically, data/icon.png and data/icon_dnd.png is the one. what do you think @mattn?

**Comment by mattn** [comment]
replaced https://github.com/mattn/growl-for-linux/commit/0a3b688608632d3a4b42690d1cd660fe207db9e6
