### ISSUE TITLE
Please provides cryptographic signature

### ISSUE THREAD

**Issue by kenhys** [mattn/growl-for-linux#63]
I want to support cryptographic signature verification in current RFS process.

ref. https://wiki.debian.org/debian/watch#Cryptographic_signature_verification

Here is the summary:

Upstream (@mattn): 
* upload a signed file (such as growl-for-linux-0.8.4.tar.gz.asc)

```
gpg2 --local-user XXX --armor --detach-sign  growl-for-linux-0.8.4.tar.gz
```

Packager (@kenhys):
* add debian/upstream/signing-key.asc (Is this key is used https://keybase.io/mattn/key.asc for signing?)
* update debian/watch to support pgpsigurlmangle option

**Comment by mattn** [comment]
Yes, please use key on keybase.

**Comment by mattn** [comment]
Ah, this is what I should do?

**Comment by mattn** [comment]
If you are okay, I'll add you to contributor of this repository.

**Comment by kenhys** [comment]
It may be short answer:
1. make dist
2. sign tar.gz
3. upload tar.gz and .asc to release page explicitly
(In another project - libhinawa's case is good example maybe. https://github.com/takaswie/libhinawa/releases)/tag/0.7.0

**Comment by mattn** [comment]
Thanks for explaining. See https://github.com/mattn/growl-for-linux/releases/tag/0.8.5

**Comment by kenhys** [comment]
Thanks. I did growl-for-linux 0.8.5 RFS process.

**Comment by kenhys** [comment]
ref. https://lists.debian.org/debian-mentors/2016/06/msg00431.html
