### ISSUE TITLE
Please release new version (0.8.5?)

### ISSUE THREAD

**Issue by kenhys** [mattn/growl-for-linux#78]
After 0.8.4 release, I think some trivial, but good enough changes to bump version are introduced.
So please consider to release 0.8.5.

Here are the changes it deserves to bump version.

Drop removed growl4linux.jpg image from the rule 
https://github.com/mattn/growl-for-linux/commit/0d2721e2f51c9c53d599866ecbfba12c44109b17

add 256x256 icon 
https://github.com/mattn/growl-for-linux/commit/03fc5948fbd9cfb9aaddcfb50e6c8e6a614276af

Use smaller image for about dialog 
https://github.com/mattn/growl-for-linux/commit/e447ac82bc663f6193a3488546a7f6bd84c990f9

OT:
Recently, growl-for-linux 0.8.4 was imported into Debian unstable, and Ubuntu 16.10 (Yakkety Yak)
Thank you for your cooperation! :smile:

**Comment by mattn** [comment]
good to hear! I'll do this.

**Comment by kenhys** [comment]
ref.
In Debian unstable
https://packages.debian.org/search?suite=sid&searchon=names&keywords=growl-for-linux

In Ubuntu
https://launchpad.net/ubuntu/+source/growl-for-linux

**Comment by kenhys** [comment]
Thanks!
 I'm happy if you also support #63 in next release.

**Comment by mattn** [comment]
done
