### ISSUE TITLE
glib-2.0 not found

### ISSUE THREAD

**Issue by horse-latitudes** [mattn/growl-for-linux#80]
Hi.
I'm trying to install via GitHub & whilst running 'configure' it's telling me:
'configure: error: Package requirements (glib-2.0) were not met:
No package 'glib-2.0' found'

However 'find' tells me it's installed at:
'/usr/share/glib-2.0
/usr/lib/i386-linux-gnu/glib-2.0
/usr/lib/x86_64-linux-gnu/glib-2.0
/usr/include/glib-2.0'

Any help appreciated. Cheers Phil.

**Comment by Flast** [comment]
IIRC, the configure uses pkg-config to find packages, so please check your installation about pkg-config.

**Comment by horse-latitudes** [comment]
yep Linuxbrew has hijacked 'pkg-config'
I tried: 'export PKG_CONFIG_PATH=/usr/bin/pkg-config:$PKG_CONFIG_PATH'
but it didn't work.
pkg-config is in /usr/bin. Linuxbrew's version is in $HOME. Would you be so kind as to offer up something I can put in my bashrc to point configure at the right pkg-config?
Any help appreciated, cheers Phil.

**Comment by horse-latitudes** [comment]
it's OK I sorted it...
