### ISSUE TITLE
No package 'sqlite3' found

### ISSUE THREAD

**Issue by ghost** [mattn/growl-for-linux#81]
when i ran ./configure 

checking for SQLITE3... no
configure: error: Package requirements (sqlite3) were not met:
No package 'sqlite3' found

but i checked  with apt 
sqlite3 is already the newest version (3.19.3-3).

**Comment by mattn** [comment]
Try to install libsqlite3-devel.

2017/11/25 午前3:53 "tribeiros" <notifications@github.com>:

**Comment by ghost** [comment]
worked , and after that i had to install libdbus-glib-1-dev too
thanks.
